%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Data generation using "jointseg"}

\documentclass{article} 
\usepackage[latin1]{inputenc}
\usepackage{color, pdfcolmk}
\usepackage{geometry}
\geometry{verbose,tmargin=2.5cm,bmargin=2.5cm,lmargin=2.5cm,rmargin=2.5cm}
\usepackage{hyperref}
\title{Generating realistic data with known truth using the \code{jointseg} package}
\author{M. Pierre-Jean, G. Rigaill, P. Neuvial}

\newcommand{\code}[1]{\texttt{#1}}

<<setup, include=FALSE, cache=FALSE, show=FALSE>>=
library(knitr)
# set global chunk options
opts_chunk$set(fig.path='fig/datGen-', fig.align='center', fig.show='hold')
options(replace.assign=TRUE,width=90)
@ 

\begin{document}

<<include=FALSE>>=
opts_chunk$set(dev='png', fig.width=5, fig.height=5)
@

\maketitle
\begin{abstract}
This vignette illustrates how the \code{jointseg} package may be used to generate a variety of copy-number profiles from the same biological ``truth''.  Such profiles have been used to compare the performance of segmentation methods \cite{pierre-jean14performance}.
\end{abstract}

\tableofcontents

\clearpage
Please see Appendix \ref{citation} for citing \code{jointseg}.

<<message=FALSE>>=
library(jointseg)
@

\section{Setup}

The parameters are defined as follows:
<<truth>>=
n <- 1e4                                 ## signal length
bkp <- c(2334, 6121)                     ## breakpoint positions
regions <- c("(1,1)", "(1,2)", "(0,2)")  ## copy number regions
@ 

<<settings>>=
ylims <- cbind(c(0, 5), c(-0.1, 1.1))
colG <- rep("#88888855", n)
hetCol <- "#00000088"
@ 

For convenience we define a custom plot function for this vignette: 
<<plottingFunction>>=
plotFUN <- function(dataSet, tumorFraction) {
  regDat <- loadCnRegionData(dataSet=dataSet, tumorFraction=tumorFraction) 
  sim <- getCopyNumberDataByResampling(n, bkp=bkp, regions=regions, regData=regDat)
  dat <- sim$profile
  wHet <- which(dat$genotype==1/2)
  colGG <- colG
  colGG[wHet] <- hetCol
  plotSeg(dat, sim$bkp, ylims=ylims, col=colGG)
}
@ 

\clearpage

\section{Affymetrix data}

<<>>=
ds <- "GSE29172"
@ 

\begin{figure}
  \centering
<<label=Affy100>>= 
tf <- 1
plotFUN(ds, tf)
@
\caption{Data set \Sexpr{ds}, \Sexpr{tf*100}\% tumor cells}
\label{fig:\Sexpr{ds}-\Sexpr{tf*100}}
\end{figure}

\begin{figure}
  \centering
<<label=Affy100b>>= 
tf <- 1
plotFUN(ds, tf)
@
\caption{Data set \Sexpr{ds}, \Sexpr{tf*100}\% tumor cells (another resampling)}
\label{fig:\Sexpr{ds}-\Sexpr{tf*100}b}
\end{figure}

\begin{figure}
  \centering
<<label=Affy70>>= 
tf <- .7
plotFUN(ds, tf)
@
\caption{Data set \Sexpr{ds}, \Sexpr{tf*100}\% tumor cells}
\label{fig:\Sexpr{ds}-\Sexpr{tf*100}}
\end{figure}


\begin{figure}
  \centering
<<label=Affy50>>= 
tf <- .5
plotFUN(ds, tf)
@
\caption{Data set \Sexpr{ds}, \Sexpr{tf*100}\% tumor cells}
\label{fig:\Sexpr{ds}-\Sexpr{tf*100}}
\end{figure}

\clearpage

\section{Illumina data}
<<>>=
ds <- "GSE11976"
@ 

\begin{figure}
  \centering
<<label=Illu100>>= 
tf <- 1
plotFUN(ds, tf)
@
\caption{Data set \Sexpr{ds}, \Sexpr{tf*100}\% tumor cells}
\label{fig:\Sexpr{ds}-\Sexpr{tf*100}}
\end{figure}

\begin{figure}
  \centering
<<label=Illu100b>>= 
tf <- 1
plotFUN(ds, tf)
@
\caption{Data set \Sexpr{ds}, \Sexpr{tf*100}\% tumor cells (another resampling)}
\label{fig:\Sexpr{ds}-\Sexpr{tf*100}b}
\end{figure}

\begin{figure}
  \centering
<<label=Illu79>>= 
tf <- .79
plotFUN(ds, tf)
@
\caption{Data set \Sexpr{ds}, \Sexpr{tf*100}\% tumor cells}
\label{fig:\Sexpr{ds}-\Sexpr{tf*100}}
\end{figure}


\begin{figure}
  \centering
<<label=Illu50>>= 
tf <- .5
plotFUN(ds, tf)
@
\caption{Data set \Sexpr{ds}, \Sexpr{tf*100}\% tumor cells}
\label{fig:\Sexpr{ds}-\Sexpr{tf*100}}
\end{figure}

\appendix

\section{Session information}
<<>>=
sessionInfo()
@ 

\section{Citing \code{jointseg}}
\label{citation}

<<message=FALSE>>=
citation("jointseg")
@ 

\bibliographystyle{plain}
\bibliography{jointSeg}

\end{document}
